# Generated by Django 4.0.3 on 2022-03-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
